# Generated by Django 4.2.6 on 2023-10-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review_pub", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paper",
            name="date_approved",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="approved date"
            ),
        ),
        migrations.AlterField(
            model_name="paper",
            name="date_submitted",
            field=models.DateTimeField(
                auto_created=True, auto_now_add=True, verbose_name="submission date"
            ),
        ),
    ]
